Global:
  use_gpu: True
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 1
  save_model_dir:  ./output/res18_fuse/
  save_epoch_step: 100
  eval_batch_step: [0, 1200]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints: #./output/res18_fuse/best_accuracy
  save_inference_dir: 
  use_visualdl: True
  infer_img: ./train_data/sample
  character_type: ch
  character_dict_path: ./train_data/dict.txt
  max_text_length: 27
  num_heads: 8
  infer_mode: False
  save_res_path: ./train_data/sample_res

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: SRN
  Transform:
  Backbone:
    name: ResNet
    layers: 18

  Neck:
  Head:
    name: FuseHead
    max_text_length: 27
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512 

Loss:
  name: AttentionLoss 

PostProcess:
  name: SRNLabelDecode
  pr_thresh: 0.8
  cooccurrence_relation_path: ./weights/cooccurrence_relation.npy
  character_dict_path: ./train_data/dict.txt
  use_space_char: False
  max_text_length: 27

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/dachuang/workspace/Pjz/Data/Ming_history/text_line   #./train_data/text_line
    label_file_list: ["./train_data/train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 32, 432]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2']  # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 1
    drop_last: False
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/dachuang/workspace/Pjz/Data/Ming_history/text_line   #./train_data/text_line
    label_file_list: ["./train_data/validation.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 32, 432]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2']  # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 0
